### ISSUE TITLE
Allow 'mapping' to be defined for more than one target type.

### ISSUE THREAD

**Issue by undiwahn** [SkywardApps/popcorn#10]
Right now Popcorn only allows configuration of a 'default' mapping; one source type to one destination type. 

This makes sense at the point of 'blind' expansion (the return result from the Api) but we need to be able to map any given source into multiple different projections, especially given that we know the destination type when we inspect properties.  So for example:

```csharp
// data object
class User{
 public Guid Id {get; set;}
 public string Name {get; set;}
 public string Email {get; set; }
}

// a projection
class UserNameOnly { 
 public Guid Id {get; set;}
 public string Name {get; set;}
}

// a different projection
class UserEmailOnly {
 public Guid Id {get; set;}
 public string Email {get; set;}
}

// Aggregation object
public class UserRelationship{
 public User Owner {get; set;}
 public User  Child {get; set;}
} 

// A projection of the aggregation, 
// projecting the User into different forms
public class UserRelationshipProjection {
 public UserNameOnly Owner {get; set;}
 public UserEmailOnly Child {get; set;}
}
```

We should be able to return a UserRelationship from an API and have the contained users correctly projected into UserNameOnly and UserEmailOnly types as expected.

We do still need the concept of a 'default' projection type to meet the requirements of the current implementation.

**Comment by alexbarbato** [comment]
Looks like @undiwahn is on this
