### ISSUE TITLE
Update to .NET Core 2.0

### ISSUE THREAD

**Issue by alexbarbato** [SkywardApps/popcorn#14]
## Possible Solution
Update dotnet sdk to 2.0

## Detailed Description
We are currently running on 1.1 and could probably do to update to the most current implementation

**Comment by alexbarbato** [comment]
Should we also consider updating the .NET Standard framework from 1.5?

**Comment by alexbarbato** [comment]
Backlogging this for now as the benefits of updating to 2.0 don't seem to outweigh the backwards compatability costs.

**Comment by undiwahn** [comment]
Eventually we may reopen this issue and integrate the change.  The reasoning for now is that we want to cast as wide a net as we can so many people can use this library.  By updating to .net core 2.0, we restrict ourselves to only projects that are *also* 2.0.  Whereas being on .net core 1.1, any 1.1 or 2.0 project can utilize it.

There are definitely benefits to 2.0, so we will want to revisit.  Possibly we need to create a separate package for 2.0 support?  This may depend on how best to handle it in nuget.
