### ISSUE TITLE
MapEntityFramework method does not allow mapping configuration

### ISSUE THREAD

**Issue by undiwahn** [SkywardApps/popcorn#15]
While the Map method on PopcornConfiguration allows you to pass in a configuration action, this ability is not present on the MapEntityFramework extension method.  This means that you cannot (easily) configure translations or other advanced properties.

## Steps to Reproduce
Try to map an entity framework object with a translation.
``
config.MapEntityFramework<Project, ProjectProjection, TestModelContext>(TestModelContext.ConfigureOptions(), 
                (definition) =>
                {
                    definition.Translate(o => o.Id, () => Guid.NewGuid());
                });
``

## Expected Behavior
You should be able to configure this in the MapEntityFramework call

## Actual Behavior
You cannot.  You have to execute a Map<> call immediately following the MapEntityFramework<> call to attach any additional configuration.

## Possible Solution
Accept a new parameter in the MapEntityFramework method (optional) that will configure the object after MapEntityFramework does its configuration. (Basically act exactly like Map after all the custom work).

**Comment by aerotog** [comment]
PR opened with requested change.

**Comment by alexbarbato** [comment]
Thanks for the PR! We wil give it a day or two for people to review.
