### ISSUE TITLE
Missing Factories tutorial

### ISSUE THREAD

**Issue by alexbarbato** [SkywardApps/popcorn#17]
## Detailed Description
In PopcornConfiguration.cs we define the ability to assign a factory, both with and without a context provided. We want to document how to use these functions so as to make them accessible to users.

## Possible Implementation
+ Add a test for the Assign Factory function that takes in a context to ExpanderTests.cs (you'll find a test for the generic AssignFactory function already exists and can be used as reference)
+ Add an example of how to use the factory assignment in the PopcornExample project if possible.
+ Add a tutorial to the PopcornExample project on how to use factories.

**Comment by chrsi** [comment]
Hey, I'd like to grab this one and started to work though the example project. As far as i understood this Factory functionality, it provides a way to specify default values for mapped entities. Are there any other interesting use cases?

**Comment by alexbarbato** [comment]
Hey thanks for offering to help!
I'm going to mark this as claimed and it's all yours.

I think you're pretty right that one way you can use the AssignFactory function is to apply default values to generated objects from the Factory. I think the potentially cooler use case, we don't have a text example of yet, is when you apply a context to the factory because you can be a bit more dynamic with the resulting object as the context doesn't necessarily have to be hard coded to a single value.

@undiwahn, please let me know if this sounds completely out in left field too please!

Let me know if that helps/doesn't and I can get you a more concrete example should the need be.
Thanks again :)

**Comment by chrsi** [comment]
I tried to find a fitting example in my last commit fdcbd35. Could someone please have a look if thats a good example? Its about employment types that, if not explicitly requested, responds with a generic "Employed" information. If it's included in the request, you'll get the detailed Information (eg. FullTime/PartTime)

**Comment by alexbarbato** [comment]
Saw your PR, thanks a ton!
Let's give it a couple of days for everyone to have a chance to review (myself included), but it looks like an awesome go from the little I've looked at so far

**Comment by chrsi** [comment]
Thanks for the Feedback, I'm glad that i could help :)

**Comment by undiwahn** [comment]
Pull request accepted and merged!
