### ISSUE TITLE
Deploy release 2.0.0

### ISSUE THREAD

**Issue by alexbarbato** [SkywardApps/popcorn#21]
## Possible Solution
Let's deploy!

## Possible Implementation
This one is farily straightforward

1. Make sure all desired code is committed to master and accurate to the release 2.0 milestone (close all issues that have been finished)
2. Update both csproj files with release information
3. Write release notes in MD
4. Push to nuget
5. Paste release notes into GitHub as a release and publish

**Comment by alexbarbato** [comment]
note to self: Make sure to update READ.ME with feature list (and any other relevant information)

**Comment by undiwahn** [comment]
Closed with commit bd3cc41ef55f49d042ef69d16cba9b0981244178
