### ISSUE TITLE
ExpandEntityFramework does not offer a way to load db context when expanding plain functions

### ISSUE THREAD

**Issue by jmathew** [SkywardApps/popcorn#24]
## Issue
Below is an example Model-Projection setup that shows the issue. See comments for details.

```
Model.cs
public Model {
    public List<SubEntity> SubEntities {get; set;}

    public List<SubEntity> FilteredSubEntities() {
           // The context will need the 'SubEntities' property loaded when
           // this function is evaluated. However, if only 'FilteredSubEntities' is
           // included in the includes, SubEntities will be 'null' and this will fail.
           return SubEntities.Where(...).ToList();
    } 
}
public ModelProjection {
     public List<SubEntity> FilteredSubEntities { get; set; }
}

public SubEntity { // Doesnt matter }
public SubEntityProjection { //Doesnt matter }
```

This is the mapping. Notice there's nothing custom about it.
```
.MapEntityFramework<Model , ModelProjection, Context>(dbContextOptionsBuilder)
.MapEntityFramework<SubEntity , SubEntityProjection, Context>(dbContextOptionsBuilder)
```

The include that does not work:
```
/api/models?include=[FilteredSubEntities]
```

However this will work but only if in this order:
```
/api/models?include=[SubEntities, FilteredSubEntities]
```

## Expected enhancement
Not sure. But something like the context being passed to functions being expanded inside the model should do the trick. Ideally, only if the context is specified in the function signature. Similar to the way dependency injection is done in Aspnet Core.

## Work around
This is a gross workaround because I'm directly using the dbcontext inside the context. The hardcoded key is the most brittle portion. I could also loop the dictionary but that would happen for every api request.

```
.Map<Model, ModelProjection>(config: (config) =>
{
    config
        .PrepareProperty("FilteredSubEntities", (destinationObject, destinationProperty, sourceObject, context) =>
        {
            if (context.ContainsKey("Db"))
            {
                var expandDb = context["Db"] as MyContext;
                expandDb.Entry(sourceObject).Collection("SubEntities").Load();
            }
        });
})
```

**Comment by alexbarbato** [comment]
@jmathew - weirdly I'm pretty sure that I got this to repro when I tried manipulating the code in ExpanderCoreTests.cs, but when I updated some things in the example project to see if I could get a repro there, things worked just fine.

Would you mind reviewing the branch 17749 with me please and see what kind of magic we have going on and whether the issue is popcorn related or not?

**Comment by alexbarbato** [comment]
Putting this back in the claimable territory as I've got other stuff for the moment. I can help with questions if anyone needs though as i did get a running start.

This should be a much easier implementation now that we've joined the netcore and net framework projects.

**Comment by jmathew** [comment]
My alternative suggestion would be to add a `PrepareEntityFramework` or `PrepareWithDbContext("MyFunctionProperty", (destinationObject, destinationProperty, sourceObject, context, dbContext)` that has an extra parameter for the dbcontext.
