### ISSUE TITLE
Publish Nuget symbols

### ISSUE THREAD

**Issue by alexbarbato** [SkywardApps/popcorn#27]
@jmathew asked a good question about Nuget symbols. Currently it doesn't seem that we push our symbols with our nuget deployments.

Do we want to add a deploy step to do so?

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages - Possible implementation

**Comment by undiwahn** [comment]
This should be resolved with the PR https://github.com/SkywardApps/popcorn/pull/53
