### ISSUE TITLE
Support 'Expanding' a Dictionary<string, ?> into a strong type

### ISSUE THREAD

**Issue by undiwahn** [SkywardApps/popcorn#29]
We want to support the scenario where the destination type is a strong type (eg 'Car') but the source is a dictionary.  The simple implementation is to take each key in the dictionary and try to write it to a property in the target type.  This is the same as Expand currently does, but instead of iterating over the source's properties we'd need to iterate over its keys.

**Comment by alexbarbato** [comment]
If no one grabs this, once I finish 30 (should be early tomorrow) I'll hop onto this as they are similar in a lot of ways.
