### ISSUE TITLE
[InternalOnly] Documentation

### ISSUE THREAD

**Issue by alexbarbato** [SkywardApps/popcorn#37]
## Possible Solution
In PR #35 / Issue #34  we added the InternalOnly attribute. We also want to include a tutorial on how this feature can be used, as well as maybe adding a bit of inline documentation.

## Possible Implementation
1. Add a tutorial on how to use the InternalOnly attribute
2. Add an example to the example project
3. We may also want to update the usage of InternalOnlyViolationException to include the name of the method/class/property that was marked InternalOnly in the message returned with the exception

**Comment by 96andrei** [comment]
I'll take a look at this later today.

**Comment by alexbarbato** [comment]
Awesome! Thanks man
