### ISSUE TITLE
Add Sort ability to blind expansion

### ISSUE THREAD

**Issue by alexbarbato** [SkywardApps/popcorn#43]
Currently the sort function will not work at all for blindly expanded objects. The big question here is do we want to support sort (and thus likely other extensions + features we add to popcorn minus the simple include expansion) for Blindly expanded objects?

## Possible Solution
Should we choose to extend the sort functionality to Blindly expanded objects, we will probably just try to sort objects normally (based on properties) and should that fail, attempt to sort blind based on dictionary values.

I could see this being a bit of a bear to keep up and possibly lead to some weird error scenarios if not implemented with some intention (just because doing things blind by nature makes them more risky)

(**Side note:** Reminder to update the tutorial when we update the sorting functionality as it currently says sorting isn't supported for blind expansion objects should we implement this)

**Comment by alexbarbato** [comment]
I can take this one if we decide it's something we'd like implemented.

**Comment by undiwahn** [comment]
I suggest we wait for the implementation of mapping dictionary -> concrete
object to come through as I hope there will be some overlap.
