### ISSUE TITLE
Need a .Net Framework implementation for Entity Framework

### ISSUE THREAD

**Issue by undiwahn** [SkywardApps/popcorn#6]
Within the dotnet implementation, we have:
- A base implementation in .Net Standard (usable by all)
- An injection layer in .Net Core for EntityFrameworkCore and AspNetCore

Many projects use the original Entity Framework and Asp.Net under .Net Framework.  We would like to add an implementation for this scenario.

Setup:
- A new .Net Framework Class Library
- Named PopcornFramework
- Base namespace Skyward.Popcorn.Framework
- Nuget references to asp.net and entity framework packages as needed.

Requirements:
- Must implement an attribute that can be applied to individual endpoints that will expand and project.  Reference Skyward.Popcorn.Core.ExpandResultAttribute for an example.
- Add an extension method to PopcornConfiguration that allows a user to enable lazy-loaded property expansion.  Reference Skyward.Popcorn.Core.EntityFrameworkCore for an example.  NOTE: It is possible that since lazy loading is actually a feature in EF, there's no real additional work needed here.

**Comment by alexbarbato** [comment]
@Eightgate is working on this

**Comment by alexbarbato** [comment]
@undiwahn - with the changes to having everything under one .NET Standard project - is this implementation still necessary?
From the write up above it would seem that we could attempt to support lazy loading natively with EF, but from what I can tell I'm not sure that would justify making a whole new implementation.

**Comment by undiwahn** [comment]
I don't believe the current implementation will work with asp.net 4 and
entity framework 6.

On Nov 10, 2017 10:10 AM, "Alex Barbato" <notifications@github.com> wrote:

@undiwahn <https://github.com/undiwahn> - with the changes to having
everything under one .NET Standard project - is this implementation still
necessary?
From the write up above it would seem that we could attempt to support lazy
loading natively with EF, but from what I can tell I'm not sure that would
justify making a whole new implementation.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/SkywardApps/popcorn/issues/6#issuecomment-343498417>,
or mute the thread

**Comment by undiwahn** [comment]
I'm working on this.
