### ISSUE TITLE
Add Authorizers to restrict access to objects

### ISSUE THREAD

**Issue by alexbarbato** [SkywardApps/popcorn#9]
### We need to be able to assign functions to restrict access to certain object, potentially based on the Context.
 
Imagine for example I'm interacting with an auction website API.  I may request the status of a particular auction, and as part of that object there is a list of 'bids' on the auction.  I should only see my own, not bids belonging to anyone else.
 
I should be able to attach a function to the 'Bid' object type to restrict it from being projected (either as a property or within a collection) if my criteria isn't met.

**Comment by undiwahn** [comment]
I'm currently implementing this!

**Comment by alexbarbato** [comment]
Code completed on 17313
